# Generated by Django 4.2 on 2024-11-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDB', '0002_site_touristique_delete_site_toutristique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_touristique',
        ),
    ]
