# Generated by Django 4.2 on 2024-11-25 10:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDB', '0004_site_touristique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assainissement',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('arrondisse', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=20)),
                ('lieu_dit', models.CharField(max_length=20)),
                ('zone_trava', models.CharField(max_length=20)),
                ('nature', models.CharField(max_length=20)),
                ('autoriser', models.CharField(max_length=5)),
                ('aménager', models.CharField(max_length=5)),
                ('année_col', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
