# Generated by Django 4.2 on 2024-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDB', '0006_alter_administration_arrondisse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='nbr_classe',
            field=models.CharField(max_length=10),
        ),
    ]
