# Generated by Django 4.2 on 2024-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDB', '0007_alter_education_nbr_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sante',
            name='catégorie',
            field=models.CharField(max_length=25),
        ),
    ]
